# Generated by Django 3.1.2 on 2021-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('mode', models.CharField(max_length=128)),
                ('cron_string', models.CharField(default=None, max_length=128, null=True)),
                ('command_ipynb', models.CharField(default=None, max_length=512, null=True)),
                ('running', models.BooleanField(default=False)),
                ('last_status', models.IntegerField(null=True)),
                ('current_status', models.IntegerField(null=True)),
                ('output', models.CharField(default=None, max_length=512, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]

