name: Docker Image CI

on:
  release:
    branches: [ main ]
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        echo $RELEASE_VERSION
        echo $GITHUB_REF
